name: urbandit-repro
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pip
  - pip:
      - torch==2.0.0
      - tensorboard
      - numpy
      - pandas
      - tqdm
      - scikit-learn

